# Generated by Django 2.1.4 on 2019-08-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meid', '0002_auto_20190824_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='pic',
            field=models.CharField(default='', max_length=255),
        ),
    ]
