# Generated by Django 2.1.4 on 2019-08-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meid', '0003_banner_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='pic',
        ),
    ]
