# Generated by Django 2.1.4 on 2019-08-26 09:43

from django.db import migrations, models
import django.db.models.deletion
import meid.models


class Migration(migrations.Migration):

    dependencies = [
        ('meid', '0004_remove_news_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=255)),
                ('satus', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'resource',
            },
            bases=(meid.models.Base, models.Model),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('resource', models.ManyToManyField(to='meid.Resource')),
            ],
            options={
                'db_table': 'role',
            },
            bases=(meid.models.Base, models.Model),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('passwd', models.CharField(max_length=255)),
                ('is_admin', models.IntegerField()),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meid.Role')),
            ],
            options={
                'db_table': 'userinfo',
            },
            bases=(meid.models.Base, models.Model),
        ),
    ]
