# Generated by Django 2.1.4 on 2019-08-29 20:40

from django.db import migrations, models
import meid.models


class Migration(migrations.Migration):

    dependencies = [
        ('meid', '0010_auto_20190829_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('pic', models.CharField(max_length=255)),
                ('goods_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'cart',
            },
            bases=(meid.models.Base, models.Model),
        ),
    ]
