# Generated by Django 2.1.4 on 2019-09-03 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meid.models


class Migration(migrations.Migration):

    dependencies = [
        ('meid', '0011_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('adress', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adress',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('tmony', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_type', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=100)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meid.Adress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
            },
            bases=(meid.models.Base, models.Model),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('name', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('user_id', models.IntegerField()),
                ('order_sn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meid.Order', to_field='order_sn')),
            ],
            options={
                'db_table': 'orderdetail',
            },
            bases=(meid.models.Base, models.Model),
        ),
    ]
