# Generated by Django 2.1.4 on 2019-09-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meid', '0012_adress_order_orderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('cityID', models.IntegerField()),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.RemoveField(
            model_name='adress',
            name='phone',
        ),
        migrations.AddField(
            model_name='cart',
            name='is_checked',
            field=models.IntegerField(default=0),
        ),
    ]
