# Generated by Django 2.1.4 on 2019-09-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meid', '0013_auto_20190904_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='cityID',
            new_name='type',
        ),
    ]
