# Generated by Django 2.1.4 on 2019-09-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meid', '0014_auto_20190904_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='adress',
            name='user',
        ),
        migrations.AddField(
            model_name='adress',
            name='city',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='district',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='email',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='is_mo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adress',
            name='mobile',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='place',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='province',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='receiver',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='tel',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
