# Generated by Django 2.1.4 on 2019-09-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meid', '0015_auto_20190904_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='is_se',
            field=models.IntegerField(default=0),
        ),
    ]
