# Generated by Django 2.1.4 on 2019-09-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meid', '0017_orderdetail_good_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
