# Generated by Django 2.1.4 on 2019-09-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meid', '0018_adress_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='com_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='is_say',
            field=models.IntegerField(default=0),
        ),
    ]
